# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS buildblocks
WORKDIR /src

# This stage is used to build the service project
COPY ["BuildingBlocks/", "./BuildingBlocks/"]
RUN dotnet restore BuildingBlocks/BuildingBlocks.sln